eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

name: Fight Dengue again Updated!!!!
number: 11111111
surname: Hurrayyyyyyyyyy.........It worked...
